import { STAGE3_INFO_TYPE, type Stage3InfoType } from './types';

export const STAGE3_COLOR_BY_INFO_TYPE = {
  [STAGE3_INFO_TYPE.HERO_ABOUT]: '#90B4EF',
  [STAGE3_INFO_TYPE.EXPERIENCE]: '#BAEFAF',
  [STAGE3_INFO_TYPE.SKILLS]: '#EDEFA6',
  [STAGE3_INFO_TYPE.PROJECTS]: '#EF9D9D',
  [STAGE3_INFO_TYPE.EDUCATION_CERTIFICATES]: '#ADA2EF',
  [STAGE3_INFO_TYPE.CONTACT]: '#EFEFEF',
};

export const STAGE3_ORDERED_INFO_TYPE: Stage3InfoType[] = [
  STAGE3_INFO_TYPE.HERO_ABOUT,
  STAGE3_INFO_TYPE.EXPERIENCE,
  STAGE3_INFO_TYPE.SKILLS,
  STAGE3_INFO_TYPE.PROJECTS,
  STAGE3_INFO_TYPE.EDUCATION_CERTIFICATES,
  STAGE3_INFO_TYPE.CONTACT,
];

export const STAGE3_LEGEND_LABEL_BY_INFO_TYPE = {
  [STAGE3_INFO_TYPE.HERO_ABOUT]: 'Hero & About',
  [STAGE3_INFO_TYPE.EXPERIENCE]: 'Experience',
  [STAGE3_INFO_TYPE.SKILLS]: 'Skills',
  [STAGE3_INFO_TYPE.PROJECTS]: 'Projects',
  [STAGE3_INFO_TYPE.EDUCATION_CERTIFICATES]: 'Education & Certificates',
  [STAGE3_INFO_TYPE.CONTACT]: 'Contact',
};
