export const CLOUDFLARE_R2_BASE_URL = 'https://pub-74aae4636bec488bb9512a996a566842.r2.dev';

const PROJECT_PATH = {
  EPIC_AI: `${CLOUDFLARE_R2_BASE_URL}/epic-ai`,
  EPIC_FINANCE: `${CLOUDFLARE_R2_BASE_URL}/epic-finance`,
};

export const PROJECT_VIDEO = {
  EPIC_AI_FEEDS: `${PROJECT_PATH.EPIC_AI}_feeds.mp4`,
  EPIC_AI_RESEARCH_CENTER: `${PROJECT_PATH.EPIC_AI}_research-center.mp4`,
  EPIC_AI_COPILOT: `${PROJECT_PATH.EPIC_AI}_copilot.mp4`,
  EPIC_AI_COMPANY_ANALYSIS: `${PROJECT_PATH.EPIC_AI}_company-analysis.mp4`,
  EPIC_FINANCE_COMPANY: `${PROJECT_PATH.EPIC_FINANCE}_company.mp4`,
  EPIC_FINANCE_INDUSTRY: `${PROJECT_PATH.EPIC_FINANCE}_industry.mp4`,
  EPIC_FINANCE_CREDIT_CARD: `${PROJECT_PATH.EPIC_FINANCE}_credit-card.mp4`,
  EPIC_FINANCE_EXPORT: `${PROJECT_PATH.EPIC_FINANCE}_export.mp4`,
  EPIC_FINANCE_HEATMAP: `${PROJECT_PATH.EPIC_FINANCE}_heatmap.mp4`,
};
